### ISSUE TITLE
layer reordering not working when dragging down

### ISSUE THREAD

**Issue by simod** [boundlessgeo/sdk#327] opened 2017-01-10 12:36 UTC
When dragging/dropping down (at least when the layer is in nested groups) the reorder doesn't happen. The layer is sometimes swapped with the other while dragging (not always) but on drop returns to it's original place

**Comment by bartvde** [comment] 2017-01-12 09:45
I cannot reproduce in SDK currently

![selection_013](https://cloud.githubusercontent.com/assets/319678/21884592/46c9db4e-d8b4-11e6-8539-3e81cd83cc0d.png)

**Comment by bartvde** [comment] 2017-04-28 12:46
Haven't been able to reproduce, so closing

**Closed by bartvde** 2017-04-28 12:46 UTC
